language: python
python: "3.6"

notifications:
    slack:
        on_success: always
        on_failure: always

sudo: false

before_install:
    - pip install numpy

install: true

script:
    - python main.py
