language: python
python: "3.6"

notifications:
    slack:
        on_success: always
        on_failure: always

before_install:
    - pip install numpy
    - pip install pytest pytest-cov
    - pip install codecov

install: true

script:
    - pytest --cov=auto_diff_pkg
after_success:
    - codecov
    - bash <(curl -s https://codecov.io/bash)
